// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO users (
    id, password_hash, name, email, phone, username, first_name, last_name,
    avatar_url, language, is_active, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, true, $11, $11)
RETURNING id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at
`

type CreateAuthUserParams struct {
	ID           pgtype.UUID        `json:"id"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Username     pgtype.Text        `json:"username"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Language     string             `json:"language"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.ID,
		arg.PasswordHash,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Language,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUser = `-- name: GetActiveUser :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND is_active = true AND deleted_at IS NULL
`

type GetActiveUserParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetActiveUser(ctx context.Context, arg GetActiveUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Email pgtype.Text `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE (email = $1 OR username = $2) AND deleted_at IS NULL
FOR UPDATE
`

type GetUserByEmailOrUsernameParams struct {
	Email    pgtype.Text `json:"email"`
	Username pgtype.Text `json:"username"`
}

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, arg GetUserByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE (username = $1 OR email = $2) AND is_active = true AND deleted_at IS NULL
`

type GetUserByLoginParams struct {
	Username pgtype.Text `json:"username"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) GetUserByLogin(ctx context.Context, arg GetUserByLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLogin = `-- name: UpdateUserLogin :one
UPDATE users SET last_login_at = $2, updated_at = $2
WHERE id = $1 AND is_active = true AND deleted_at IS NULL
RETURNING id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserLoginParams struct {
	ID          pgtype.UUID        `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateUserLogin(ctx context.Context, arg UpdateUserLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLogin, arg.ID, arg.LastLoginAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $2, updated_at = $3 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID        `json:"id"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    avatar_url = COALESCE($3, avatar_url),
    language = COALESCE($4, language),
    name = BTRIM(CONCAT_WS(' ',
        COALESCE($1, first_name),
        COALESCE($2, last_name)
    )),
    updated_at = $5
WHERE id = $6 AND is_active = true AND deleted_at IS NULL
RETURNING id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	FirstName pgtype.Text        `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	Language  pgtype.Text        `json:"language"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
