// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users SET is_active = true, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at
`

type ActivateUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, activateUser, arg.ID, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPendingUser = `-- name: CreatePendingUser :one
INSERT INTO users (
    id, email, password_hash, name, phone, username, first_name, last_name,
    avatar_url, language, is_active, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, false, $11, $11)
RETURNING id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at
`

type CreatePendingUserParams struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	Username     pgtype.Text        `json:"username"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Language     string             `json:"language"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createPendingUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Phone,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Language,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (id, user_id, refresh_token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, refresh_token_hash, device_id, device_name, platform, expires_at, created_at, revoked_at
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.DeviceName,
		&i.Platform,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, refresh_token_hash, device_id, device_name, platform, expires_at, created_at, revoked_at FROM user_sessions
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL AND expires_at > $3
`

type GetActiveSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.DeviceName,
		&i.Platform,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveUser = `-- name: GetActiveUser :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND is_active = true AND deleted_at IS NULL
`

type GetActiveUserParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetActiveUser(ctx context.Context, arg GetActiveUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRegistrationUserForUpdate = `-- name: GetRegistrationUserForUpdate :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE (phone = $1 OR username = $2) AND deleted_at IS NULL
FOR UPDATE
`

type GetRegistrationUserForUpdateParams struct {
	Phone    pgtype.Text `json:"phone"`
	Username pgtype.Text `json:"username"`
}

func (q *Queries) GetRegistrationUserForUpdate(ctx context.Context, arg GetRegistrationUserForUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, getRegistrationUserForUpdate, arg.Phone, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, device_id, device_name, platform, expires_at, created_at, revoked_at FROM user_sessions
WHERE refresh_token_hash = $1 AND revoked_at IS NULL AND expires_at > $2 FOR UPDATE
`

type GetSessionByRefreshHashParams struct {
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, arg GetSessionByRefreshHashParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, arg.RefreshTokenHash, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.DeviceName,
		&i.Platform,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE (username = $1 OR phone = $2 OR email = $3) AND deleted_at IS NULL
FOR UPDATE
`

type GetUserByIdentifierParams struct {
	Username pgtype.Text `json:"username"`
	Phone    pgtype.Text `json:"phone"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) GetUserByIdentifier(ctx context.Context, arg GetUserByIdentifierParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, arg.Username, arg.Phone, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at FROM users WHERE phone = $1 AND deleted_at IS NULL
`

type GetUserByPhoneParams struct {
	Phone pgtype.Text `json:"phone"`
}

func (q *Queries) GetUserByPhone(ctx context.Context, arg GetUserByPhoneParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeActiveSession = `-- name: RevokeActiveSession :exec
UPDATE user_sessions SET revoked_at = $2 WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeActiveSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeActiveSession(ctx context.Context, arg RevokeActiveSessionParams) error {
	_, err := q.db.Exec(ctx, revokeActiveSession, arg.UserID, arg.RevokedAt)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE user_sessions SET revoked_at = $3
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionRefresh = `-- name: RotateSessionRefresh :one
UPDATE user_sessions SET refresh_token_hash = $2, expires_at = $3
WHERE id = $1 AND refresh_token_hash = $4 AND revoked_at IS NULL AND expires_at > $5
RETURNING id, user_id, refresh_token_hash, device_id, device_name, platform, expires_at, created_at, revoked_at
`

type RotateSessionRefreshParams struct {
	ID                 pgtype.UUID        `json:"id"`
	RefreshTokenHash   string             `json:"refresh_token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	RefreshTokenHash_2 string             `json:"refresh_token_hash_2"`
	ExpiresAt_2        pgtype.Timestamptz `json:"expires_at_2"`
}

func (q *Queries) RotateSessionRefresh(ctx context.Context, arg RotateSessionRefreshParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefresh,
		arg.ID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.RefreshTokenHash_2,
		arg.ExpiresAt_2,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.DeviceName,
		&i.Platform,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updatePendingUser = `-- name: UpdatePendingUser :one
UPDATE users SET
    email = $2, password_hash = $3, name = $4, phone = $5, username = $6,
    first_name = $7, last_name = $8, avatar_url = $9, language = $10,
    is_active = false, updated_at = $11
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UpdatePendingUserParams struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	Username     pgtype.Text        `json:"username"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Language     string             `json:"language"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePendingUser(ctx context.Context, arg UpdatePendingUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePendingUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Phone,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Language,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLogin = `-- name: UpdateUserLogin :one
UPDATE users SET last_login_at = $2, updated_at = $2 WHERE id = $1 RETURNING id, email, password, password_hash, name, phone, username, first_name, last_name, avatar_url, language, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserLoginParams struct {
	ID          pgtype.UUID        `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateUserLogin(ctx context.Context, arg UpdateUserLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLogin, arg.ID, arg.LastLoginAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Language,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $2, updated_at = $3 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID        `json:"id"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPhone = `-- name: UpdateUserPhone :execrows
UPDATE users SET phone = $2, updated_at = $3 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPhoneParams struct {
	ID        pgtype.UUID        `json:"id"`
	Phone     pgtype.Text        `json:"phone"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPhone, arg.ID, arg.Phone, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userPhoneExistsOther = `-- name: UserPhoneExistsOther :one
SELECT EXISTS(SELECT 1 FROM users WHERE phone = $1 AND id <> $2 AND deleted_at IS NULL)
`

type UserPhoneExistsOtherParams struct {
	Phone pgtype.Text `json:"phone"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UserPhoneExistsOther(ctx context.Context, arg UserPhoneExistsOtherParams) (bool, error) {
	row := q.db.QueryRow(ctx, userPhoneExistsOther, arg.Phone, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
