// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type GroupInvitation struct {
	ID            pgtype.UUID        `json:"id"`
	GroupID       pgtype.UUID        `json:"group_id"`
	InvitedBy     pgtype.UUID        `json:"invited_by"`
	Phone         pgtype.Text        `json:"phone"`
	Role          interface{}        `json:"role"`
	TokenHash     pgtype.Text        `json:"token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt    pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	InvitedUserID pgtype.UUID        `json:"invited_user_id"`
	Email         pgtype.Text        `json:"email"`
	Status        string             `json:"status"`
	RespondedAt   pgtype.Timestamptz `json:"responded_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

type GroupMember struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Username  string             `json:"username"`
	Role      interface{}        `json:"role"`
	IsOwner   bool               `json:"is_owner"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Notification struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Type      interface{}        `json:"type"`
	ActionUrl pgtype.Text        `json:"action_url"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type NotificationRecipient struct {
	ID             int64              `json:"id"`
	NotificationID int64              `json:"notification_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	IsRead         bool               `json:"is_read"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

type Order struct {
	ID    int64          `json:"id"`
	Total pgtype.Numeric `json:"total"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Password     pgtype.Text        `json:"password"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	Username     pgtype.Text        `json:"username"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Language     string             `json:"language"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
