// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (total)
VALUES ($1::float8)
RETURNING id, total::float8 AS total
`

type CreateOrderParams struct {
	Total float64 `json:"total"`
}

type CreateOrderRow struct {
	ID    int64   `json:"id"`
	Total float64 `json:"total"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.Total)
	var i CreateOrderRow
	err := row.Scan(&i.ID, &i.Total)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :one
DELETE FROM orders
WHERE id = $1
RETURNING id
`

type DeleteOrderParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteOrder(ctx context.Context, arg DeleteOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteOrder, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, total::float8 AS total
FROM orders
WHERE id = $1
`

type GetOrderByIDParams struct {
	ID int64 `json:"id"`
}

type GetOrderByIDRow struct {
	ID    int64   `json:"id"`
	Total float64 `json:"total"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, arg.ID)
	var i GetOrderByIDRow
	err := row.Scan(&i.ID, &i.Total)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, total::float8 AS total
FROM orders
ORDER BY id
`

type ListOrdersRow struct {
	ID    int64   `json:"id"`
	Total float64 `json:"total"`
}

func (q *Queries) ListOrders(ctx context.Context) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(&i.ID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET total = $1::float8
WHERE id = $2
RETURNING id, total::float8 AS total
`

type UpdateOrderParams struct {
	Total float64 `json:"total"`
	ID    int64   `json:"id"`
}

type UpdateOrderRow struct {
	ID    int64   `json:"id"`
	Total float64 `json:"total"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.Total, arg.ID)
	var i UpdateOrderRow
	err := row.Scan(&i.ID, &i.Total)
	return i, err
}
