// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password, name, language, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, password, name
`

type CreateUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	Email     pgtype.Text        `json:"email"`
	Password  pgtype.Text        `json:"password"`
	Name      pgtype.Text        `json:"name"`
	Language  string             `json:"language"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CreateUserRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	Name     pgtype.Text `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Language,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, name
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Email pgtype.Text `json:"email"`
}

type GetUserByEmailRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	Name     pgtype.Text `json:"name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, name
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID pgtype.UUID `json:"id"`
}

type GetUserByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	Name     pgtype.Text `json:"name"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password, name
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at
`

type ListUsersRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	Name     pgtype.Text `json:"name"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteUserParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password, name
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name pgtype.Text `json:"name"`
}

type UpdateUserNameRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	Name     pgtype.Text `json:"name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i UpdateUserNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
	)
	return i, err
}
