// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, avatar_url
FROM users
WHERE deleted_at IS NULL
  AND is_active
  AND (
    lower(COALESCE(username, '')) LIKE '%' || lower($1) || '%'
    OR lower(COALESCE(email, '')) LIKE '%' || lower($1) || '%'
  )
ORDER BY username NULLS LAST, email NULLS LAST
LIMIT 20
`

type SearchUsersParams struct {
	Query string `json:"query"`
}

type SearchUsersRow struct {
	ID        pgtype.UUID `json:"id"`
	Username  pgtype.Text `json:"username"`
	Email     pgtype.Text `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
